

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_settingsWindow(object):
    def setupUi(self, settingsWindow):
        settingsWindow.setObjectName("settingsWindow")
        settingsWindow.resize(800, 696)
        self.centralwidget = QtWidgets.QWidget(parent=settingsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 10, 731, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_2 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(400, 130, 361, 301))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.thumbsDown = QtWidgets.QComboBox(parent=self.gridLayoutWidget)
        self.thumbsDown.setObjectName("thumbsDown")
        self.gridLayout.addWidget(self.thumbsDown, 1, 0, 1, 1)
        self.victory = QtWidgets.QComboBox(parent=self.gridLayoutWidget)
        self.victory.setObjectName("victory")
        self.gridLayout.addWidget(self.victory, 0, 1, 1, 1)
        self.pointingUp = QtWidgets.QComboBox(parent=self.gridLayoutWidget)
        self.pointingUp.setObjectName("pointingUp")
        self.gridLayout.addWidget(self.pointingUp, 1, 1, 1, 1)
        self.thumbsUp = QtWidgets.QComboBox(parent=self.gridLayoutWidget)
        self.thumbsUp.setObjectName("thumbsUp")
        self.gridLayout.addWidget(self.thumbsUp, 0, 0, 1, 1)
        self.saveSettings = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.saveSettings.setObjectName("saveSettings")
        self.gridLayout.addWidget(self.saveSettings, 2, 0, 1, 2)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(30, 130, 371, 471))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(parent=self.gridLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 2)
        self.label_5 = QtWidgets.QLabel(parent=self.gridLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 1, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_4 = QtWidgets.QLabel(parent=self.gridLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_6 = QtWidgets.QLabel(parent=self.gridLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_7 = QtWidgets.QLabel(parent=self.gridLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 1, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter)
        settingsWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=settingsWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        settingsWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=settingsWindow)
        self.statusbar.setObjectName("statusbar")
        settingsWindow.setStatusBar(self.statusbar)

        self.retranslateUi(settingsWindow)
        QtCore.QMetaObject.connectSlotsByName(settingsWindow)

    def retranslateUi(self, settingsWindow):
        _translate = QtCore.QCoreApplication.translate
        settingsWindow.setWindowTitle(_translate("settingsWindow", "Settings"))
        self.label.setText(_translate("settingsWindow", "Használati Útmutató"))
        self.label_2.setText(_translate("settingsWindow", "Vezérlőpult"))
        self.saveSettings.setText(_translate("settingsWindow", "PushButton"))
        self.label_3.setText(_translate("settingsWindow", "hasbara"))
        self.label_5.setText(_translate("settingsWindow", "Victory"))
        self.label_4.setText(_translate("settingsWindow", "<html><head/><body><p>Thumbs Up</p><p><br/></p></body></html>"))
        self.label_6.setText(_translate("settingsWindow", "Thumbs Down"))
        self.label_7.setText(_translate("settingsWindow", "Pointing Up"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    settingsWindow = QtWidgets.QMainWindow()
    ui = Ui_settingsWindow()
    ui.setupUi(settingsWindow)
    settingsWindow.show()
    sys.exit(app.exec())
